---
# -------------------------------
# ClusterIssuer: Let's Encrypt (Production)
# -------------------------------
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-webapps        # Cluster-wide issuer (usable in any namespace)
spec:
  acme:
    # 🔹 ACME server endpoint for production certificates
    # For staging/testing (avoid rate limits), use:
    # https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email address for Let's Encrypt notifications (expiry, issues, etc.)
    email: pagidimariuday@gmail.com

    # Secret where the private key for the ACME account will be stored
    privateKeySecretRef:
      name: letsencrypt-webapps

    # Solver configuration: use HTTP-01 challenge via Ingress
    solvers:
      - http01:
          ingress:
            class: nginx            # Matches ingressClassName: nginx
